sudo: required
services:
  - docker

before_install:
  - docker build -t joel/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true joel/react-test npm test

after_success:
  - docker build -t joelmukono/multi-client ./client
  - docker build -t joelmukono/multi-nginx ./nginx
  - docker build -t joelmukono/multi-server ./server
  - docker build -t joelmukono/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_ID" --password-stdin

  - sudo docker push joelmukono/multi-client
  - sudo docker push joelmukono/multi-nginx
  - sudo docker push joelmukono/multi-server
  - sudo docker push joelmukono/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env : Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-500350084356
  bucket_path: docker-multi
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY