sudo: required
services:
  - docker

before_install:
  - docker build -t joel/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true joel/react-test npm test

after_success:
  - docker build -t joel/multi-client ./client
  - docker build -t joel/multi-nginx ./nginx
  - docker build -t joel/multi-server ./server
  - docker build -t joel/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_ID" --password-stdin

  - sudo docker push joel/multi-client
  - sudo docker push joel/multi-nginx
  - sudo docker push joel/multi-server
  - sudo docker push joel/multi-worker
  


